### ISSUE TITLE
Dependies not installed through composer

### ISSUE THREAD

**Issue by m6w6** [pr0ggy/peridot-scenarios#1]
Probably due to missing `composer.json` in master?

**Comment by pr0ggy** [comment]
Quite possibly...I've been waiting for the Peridot core team to get back with me on my pull request.  The plugin requires some minor changes to core that haven't been merged yet but I was told my pull request hadn't been forgotten about (granted that was 5 months ago...).  I may ping the pull request ticket again just to see if anything further needs to be done on my end.  Thanks for reaching out, I'll definitely update this issue once the core changes have been settled!

**Comment by m6w6** [comment]
Someone in #composer pointed out, that the problem is rather that deps are listed in require-dev.
